RISCV64: add buildroot toolchain support
To work this out (only riscv64 and not yet riscv32) I needed to workaround
3 issues in:

1) GCC fails to build GLIBC without warning (I add to --disable-werror to configure)
I think that GCC fails to see that size of -1L is same as a pointer. log is:
../sysdeps/unix/sysv/linux/mmap64.c: In function ‘__mmap64’:
../sysdeps/unix/sysv/linux/mmap64.c:45:12: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
    return (void *) INLINE_SYSCALL_ERROR_RETURN_VALUE (EINVAL);

2) Faild to vuild stage 1 compiler (aka inital gcc) due to misssing file
make[3]: *** No rule to make target '../../gcc/testsuite/selftests', needed by 's-selftest'.  Stop.
make[3]: *** Waiting for unfinished jobs....

3) missing kernel file needed by linux headers, add an empty one arch/riscv/include/uapi/asm/setup.h
scripts/Makefile.headersinst:72: *** Some mandatory headers (setup.h) are missing in arch/riscv/include/uapi/asm.  Stop.
scripts/Makefile.headersinst:26: recipe for target 'asm' failed

Note:
Still with this kernel spike is not booting, need to go back to master (4.6.y)

Signed-off-by: Noam Camus <noamca@mellanox.com>